### ISSUE TITLE
uftrace exit code and return values

### ISSUE THREAD

**Issue by clementguidi** [namhyung/uftrace#1649]
It is possible for uftrace to return an exit code of `-1`, which doesn't make sense in the shell. See for example the following execution:

```
main() 
{
    return command_record() 
    {
        if (create_directory(opts->dirname) < 0)
            return -1;
    } => -1
} => -1
```

I didn't check if there are any other locations where we return `-1`.

There is a confusion between shell exit codes (positive on error) and C return codes (negative on error). **Is there a specification of which functions should return shell exit codes** (e.g. `main()`, `command_*()`) instead of usual C return values?

For example, `do_main_loop()` and `stop_tracing()` return shell codes even though they are not 'exit' functions, they are part of the normal execution.

**Comment by namhyung** [comment]
Yeah, probably due to some code refactoring.  I'm not sure how much it matters.  The shell should consider any non-zero value as a failure, right?  But, if you are really concerning, we can add a wrapper for the `command_*()` functions to return a proper shell exit code and let other functions forget about it. :)

**Comment by clementguidi** [comment]
> The shell should consider any non-zero value as a failure, right?

Yes, so no big deal. I stumbled upon this when defining return values for the client in `command_live()`. I will return shell exit codes for now.
