### ISSUE TITLE
Give monotonic time offset from real time. 

### ISSUE THREAD

**Issue by MatthewKhouzam** [namhyung/uftrace#1916]
It would be nice to have the option to get the offset between `clock_monotonic` and `clock_realtime`. There is a simple-ish solution.

When uftrace starts, record quickly both `clock_realtime` and `clock_monotonic`. In task.txt, the timestamps can then be offset and the traces can then be correlated with lttng traces as well as system logs.

**Comment by namhyung** [comment]
Sounds good.  I think we can add something in the info file where we have record data and elapsed time.

**Comment by honggyukim** [comment]
Hi @MatthewKhouzam,

You explained this issue but I actually couldn't fully understand what the problem is. Could you please explain the following questions?
1. What's the meaning of the offset between `clock_monotonic` and `clock_realtime`?
2. Why this offset adjustment is needed for lttng?
3. Is is possible to change the way to get timestamps from lttng itself simply with either `CLOCK_MONOTONIC` or `CLOCK_REALTIME`?

Thanks.

**Comment by honggyukim** [comment]
Hi @MatthewKhouzam, you may want to have #1923. Please have a look. This patch simply prints the UTC offset, but we might be able to provide a tool that does post processing for each `<tid>.dat` so that you can avoid time adjustment whenever you open tracecompass.

**Comment by honggyukim** [comment]
Another idea is that you can modify uftrace parser of tracecompass so that it can understand this new info field and use it for automatic time adjustment.
