### ISSUE TITLE
Don't colour stderr output red

### ISSUE THREAD

**Issue by RalphCorderoy** [namhyung/uftrace#237]
`uftrace record a.out` when a.out wasn't built for profiling gives a bright error message on stderr.
Please don't add colour to stderr messages, that's not the Unix way, and it isn't needed for these messages to be noticed.
If every command decided to colour code its output based on its author's view of what looked good we'd be blinded by the rainbow when trying to read the TTY.
If a user wants stderr in colour then they can easily add it themselves.

**Comment by namhyung** [comment]
Thanks for your suggestion.  The output from uftrace tends to be verbose since there are so many traces during execution.  So it uses colour error message to be noticed easily, but you can disable it with `--color no` option.  But I also think that it needs to differentiate runtime errors from user errors.  For runtime errors it'd be nice to use coloured output, but probably not for user errors like you said.

Btw, is there any practical problem of using coloured error messages except for not being the Unix way?

**Comment by RalphCorderoy** [comment]
If script(1) is being used them they clutter the resulting ./typescript with the escape codes that are a bit tedious to remove so a text file can result. (Turning the CRLF into LF is trivial.)

**Comment by namhyung** [comment]
I wasn't aware of the script(1), thanks for the info.  Anyway basically uftrace tries to give more info to user using colour so I'm not sure not using colour on stderr makes much difference.  It does check the stdout and stderr being a TTY before using colour but it won't work for script(1) still..
